name: Publish new package release
on:
  pull_request:
    types:
      - closed
    branches:
      - main



jobs:

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - run: python -m build --sdist --wheel
      - run: twine check --strict dist/*
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist


  release-new-version:
    needs: package
    runs-on: ubuntu-latest
    permissions:
      contents: write # for making GitHub Releases
    steps:
      - uses: hmp/.github/workflows/request-version.yml@main
        with:
          version_number: .github/labeler.yml
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ version_number }}
          release_name: Release ${{ version_number }}

  pypi-upload:
    needs: release-new-version
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # for trusted publishing
    environment:
      name: pypi
      url: https://pypi.org/p/hmp
    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1


