# Test is the main functions still work as they should after every push
name: Test if the code is working
on: #Whenever there is a push to the main branch
  push:
    branches:
      - main

jobs:
  run_test: #Run the notebook and create an artifact file with all the outputs.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: yaananth/run-notebook@v2
        env:
          RUNNER: ${{ toJson(runner) }}
          # SECRETS: ${{ toJson(secrets) }} ##Not sure this is needed, as there might not be any secrets.
          GITHUB: ${{ toJson(github) }}
        with:
          notebook: "tutorials/Workshop/Package_testing.ipynb"
          isReport: False
          poll: True
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: output
          path: ${{ RUNNER.temp }}/nb-runner
        env:
          RUNNER: ${{ toJson(runner) }}

# have another job compare the artifact file resulted with a template file containg the expected output
